### ISSUE TITLE
Updated readMe How to use

### ISSUE THREAD

**Issue by arbyruns** [swwol/SwiftOpenColor#1]
# SwiftOpenColor

The colors from https://yeun.github.io/open-color/ in a big enum.

# Installation

## Swift Package Manager

Using Swift Package Manager, add it as a Swift Package in Xcode 11.0 or later, select `File > Swift Packages > Add Package Dependency...` and add the repository URL:

```
https://github.com/swwol/SwiftOpenColor.git
```

# How To Use

1. Begin by importing SwiftOpenColor

```
import SwiftOpenColor
```

2. Use in place where you would a color

```swift
Text("Hello, World!")
    .foregroundColor(Color(UIColor.oc_blue6))
```

```swift
    RoundedRectangle(cornerRadius: 13)
        .fill(Color(UIColor.oc_red4))
        .frame(width: 55, height: 55, alignment: .center)
}
```

**Comment by swwol** [comment]
thanks!
